name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT_ID: tourtimegolf
  REGION:	us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/tourtimegolf/tt-api
  
jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
            credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - uses: docker/build-push-action@v2
        if: steps.cz.outcome == 'success'
        with:
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}/tt-api:latest 
          #  ${{ env.GAR_LOCATION }}/tt-api:${{ steps.cz.outputs.version }}
          # target: prod

      # - name: Build image - latest
      #   run: docker build -t ${{ env.GAR_LOCATION }}/tt-api:latest ./
      #   # working-directory: ./

      # - name: Push image - latest
      #   run: docker push ${{ env.GAR_LOCATION }}/tt-api:latest

      # - name: Build image - semver
      #   run: docker build -t ${{ env.GAR_LOCATION }}/tt-api:${{ steps.cz.outputs.version }} ./

      # - name: Push image - semver
      #   run: docker push ${{ env.GAR_LOCATION }}/tt-api:${{ steps.cz.outputs.version }}     
        #${{ github.sha }}

  # deploy-dev:
  #   if: contains(github.ref, 'heads')
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-push-artifact
  #   steps:
  #     - uses: actions/checkout@v3        
  #       with:
  #         repository: sprintbased/gitops-argocd-sops
  #         ref: master
  #         token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
  #         working-directory: sprintbased/gitops-argocd-sops/overlays/production

  #     - uses: imranismail/setup-kustomize@v1
  #       with:
  #         kustomize-version: 4.0.0

  #     - run: kustomize edit set image ${{ env.GAR_LOCATION }}/tt-api:sha-${{ github.sha }}
        
  #     - run: |    

  #         git config user.email "rob.runka@sprintbased.com"
  #         git config user.name "sprintbased"
  #         git commit -am "Update image to ${{ env.GAR_LOCATION }}/tt-api:sha-${{ github.sha }}"
  #         git pull --rebase
  #         git push        